/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AskNORCRouteImport } from './routes/askNORC'
import { Route as NORCagentRouteImport } from './routes/NORCagent'
import { Route as IndexRouteImport } from './routes/index'

const AskNORCRoute = AskNORCRouteImport.update({
  id: '/askNORC',
  path: '/askNORC',
  getParentRoute: () => rootRouteImport,
} as any)
const NORCagentRoute = NORCagentRouteImport.update({
  id: '/NORCagent',
  path: '/NORCagent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NORCagent': typeof NORCagentRoute
  '/askNORC': typeof AskNORCRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NORCagent': typeof NORCagentRoute
  '/askNORC': typeof AskNORCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NORCagent': typeof NORCagentRoute
  '/askNORC': typeof AskNORCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/NORCagent' | '/askNORC'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/NORCagent' | '/askNORC'
  id: '__root__' | '/' | '/NORCagent' | '/askNORC'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NORCagentRoute: typeof NORCagentRoute
  AskNORCRoute: typeof AskNORCRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/askNORC': {
      id: '/askNORC'
      path: '/askNORC'
      fullPath: '/askNORC'
      preLoaderRoute: typeof AskNORCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NORCagent': {
      id: '/NORCagent'
      path: '/NORCagent'
      fullPath: '/NORCagent'
      preLoaderRoute: typeof NORCagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NORCagentRoute: NORCagentRoute,
  AskNORCRoute: AskNORCRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
